### ISSUE TITLE
Optimise build and test process

### ISSUE THREAD

**Issue by geekyang95** [cocalele/PureFlash#1]
1. Need a single script to build and run project. It will be convenient.
2. For now, programs run as kernel model, not convenient for debug purpose. Any planns to run as user space program?

**Comment by cocalele** [comment]
> 1. Need a single script to build and run project. It will be convenient.
   for build, it's not too complex, the problem is we lack a documentation to explain it. In fact, only one CMakeLists.txt to build. I'll add the following the build to process to build_and_run.txt soon.
```
    # git clone https://github.com/cocalele/PureFlash.git
    # cd PureFlash && mkdir build && cd build
    # cmake .. -GNinja -CMAKE_BUILD_TYPE=Debug
    # ninja
```

for Question 2, if you follow the above build process, you will see only user space module are generated. Still two things to explain,
1) kernel module is the kernel driver, we will provide in future. but for now, please ignore it.
2) for debug convenience, my plan is to provide a VM image, so the new guys can try it immediately.
