### ISSUE TITLE
Project merge

### ISSUE THREAD

**Issue by geekyang95** [cocalele/PureFlash#4]
As PureFlash is combined of different projects, but only PureFlash now, need to do some changes.
1. cmake files:
    Cmake project files need to remove unneccesary project settings.
2. thirdparty:
    A common thirdparty is needed. move thirdparty from s5afs to root directory
3. compiler flags:
    Need a unique compiler flags for all project, suggested to put it in root CMakeLists

**Comment by cocalele** [comment]
Good suggestion. There are too many historical problems.
But some projects may useful in near future, include
S5bd, the user space client library, which will be used by qemu or other hypervisor.
sld/driver, the kernel space client, which map a volume as block device in system
sld/s5bd-cli, is the CLI to manage s5 cluster.
sld/bdd, looks useless and can be removed.

So, I suggest to keep the useful project as a placeholder since they are must necessary before first release.

**Comment by geekyang95** [comment]
Yes, keep directories as now it is. But only cmake settings and the thirdparty changes

**Comment by cocalele** [comment]
I have changed change location of thirdParty and do CMakeLists.txt modify in my local branch. I'll push to master soon.
